spring:
  application:
    name: spring-security-demo-1
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/spring-security-demo-1
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
